package com.mobilekinetic.agent.data.memory

import android.content.Context
import android.util.Log
import androidx.hilt.work.HiltWorker
import androidx.work.CoroutineWorker
import androidx.work.WorkerParameters
import com.mobilekinetic.agent.data.preferences.SettingsRepository
import dagger.assisted.Assisted
import dagger.assisted.AssistedInject
import kotlinx.coroutines.flow.first
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@HiltWorker
class DecayWorker @AssistedInject constructor(
    @Assisted appContext: Context,
    @Assisted workerParams: WorkerParameters,
    private val decayEngine: MemoryDecayEngine,
    private val settingsRepository: SettingsRepository
) : CoroutineWorker(appContext, workerParams) {

    companion object {
        private const val TAG = "DecayWorker"
        const val WORK_NAME = "memory_decay_daily"
        private const val PREFS_NAME = "decay_worker_state"
        private const val KEY_RUN_COUNT = "run_count"
        private const val UPDATE_CYCLE_DAYS = 3
    }

    override suspend fun doWork(): Result {
        return try {
            Log.i(TAG, "Starting daily decay pass")
            decayEngine.runDecayPass()
            Log.i(TAG, "Decay pass complete")

            // Check if auto-update is enabled and if this is a 3rd-day cycle
            checkAutoUpdateTrigger()

            Result.success()
        } catch (e: Exception) {
            Log.e(TAG, "Decay pass failed", e)
            Result.retry()
        }
    }

    private suspend fun checkAutoUpdateTrigger() {
        try {
            val autoUpdateEnabled = settingsRepository.autoUpdateAfterDecay.first()
            if (!autoUpdateEnabled) {
                Log.i(TAG, "Auto-update after decay is disabled")
                return
            }

            // Increment and read run counter
            val prefs = applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            val runCount = prefs.getInt(KEY_RUN_COUNT, 0) + 1
            prefs.edit().putInt(KEY_RUN_COUNT, runCount).apply()

            Log.i(TAG, "Decay run count: $runCount (triggers every $UPDATE_CYCLE_DAYS)")

            if (runCount % UPDATE_CYCLE_DAYS == 0) {
                Log.i(TAG, "3rd-day cycle reached -- writing update trigger")
                writeUpdateTrigger()
            }
        } catch (e: Exception) {
            Log.e(TAG, "Auto-update check failed", e)
        }
    }

    private fun writeUpdateTrigger() {
        try {
            val homeDir = File(applicationContext.filesDir, "home")
            val triggerFile = File(homeDir, "HEARTBEAT_UPDATE_TRIGGER.md")
            val timestamp = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())

            triggerFile.writeText("""
# Update Trigger -- Auto-Generated by DecayWorker
## Time: $timestamp
## Reason: 3rd-day post-context-treatment update cycle

Context treatment (memory decay) has just completed.
This is your scheduled self-update window.

## Instructions
1. Review your RAG notes for any pending changes
2. Check ~/Factory/ for any TODO items
3. If changes are needed: edit, commit, push, preflight, build, install
4. If no changes needed: log "heartbeat complete, no updates" and delete this file
5. Delete this file when done

## Safety
- Run preflight.py before any update
- All standard safety gates apply (battery, network, speed)
""".trimIndent())

            Log.i(TAG, "Update trigger written to ${triggerFile.absolutePath}")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to write update trigger", e)
        }
    }
}
