package com.mobilekinetic.agent.data.tts

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.PreferenceDataStoreFactory
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.floatPreferencesKey
import androidx.datastore.preferences.core.stringPreferencesKey
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Secure TTS Settings Repository
 *
 * Stores TTS configuration securely using:
 * - DataStore for all preferences (voice, speed, enabled state, encrypted server URL)
 * - Android Keystore + AES-256-GCM for encrypting the server URL
 *
 * The server URL is encrypted via Android Keystore since it may contain
 * sensitive network info. Other settings use plain DataStore for efficiency.
 *
 * Migrated from EncryptedSharedPreferences / MasterKey (deprecated) to direct
 * Android Keystore + DataStore.
 */
class TtsSettingsRepository(private val context: Context) {
    companion object {
        private const val TAG = "TtsSettingsRepository"
        private const val KEYSTORE_ALIAS = "tts_server_url_key"
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val CIPHER_TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH = 128

        // DataStore keys
        private val KEY_ENCRYPTED_SERVER_URL = stringPreferencesKey("encrypted_server_url")
        private val KEY_VOICE = stringPreferencesKey("voice")
        private val KEY_SPEED = floatPreferencesKey("speed")
        private val KEY_ENABLED = booleanPreferencesKey("enabled")

        // Singleton DataStore — centralized under ~/home/Memory/DataStore/
        @Volatile
        private var dataStoreInstance: DataStore<Preferences>? = null

        private fun getOrCreateDataStore(context: Context): DataStore<Preferences> {
            return dataStoreInstance ?: synchronized(this) {
                dataStoreInstance ?: run {
                    val appContext = context.applicationContext
                    val newDir = File(appContext.filesDir, "home/Memory/DataStore").apply { mkdirs() }
                    val newFile = File(newDir, "tts_settings.preferences_pb")
                    // One-time migration from old default path
                    if (!newFile.exists()) {
                        val oldFile = File(appContext.filesDir, "datastore/tts_settings.preferences_pb")
                        if (oldFile.exists()) oldFile.copyTo(newFile)
                    }
                    PreferenceDataStoreFactory.create(
                        produceFile = { newFile }
                    ).also { dataStoreInstance = it }
                }
            }
        }
    }

    // DataStore for all settings — centralized under home for backup coverage
    private val dataStore: DataStore<Preferences> = getOrCreateDataStore(context)

    // Android Keystore for AES-256-GCM key management
    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
    }

    /**
     * Get or generate the AES-256-GCM secret key from Android Keystore.
     */
    private fun getOrCreateSecretKey(): SecretKey {
        keyStore.getEntry(KEYSTORE_ALIAS, null)?.let { entry ->
            return (entry as KeyStore.SecretKeyEntry).secretKey
        }

        val keyGen = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER
        )
        val spec = KeyGenParameterSpec.Builder(
            KEYSTORE_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .build()

        keyGen.init(spec)
        return keyGen.generateKey()
    }

    /**
     * Encrypt a plaintext string using AES-256-GCM.
     * Returns Base64-encoded string with IV prepended to ciphertext.
     */
    private fun encryptValue(plaintext: String): String {
        val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateSecretKey())
        val iv = cipher.iv // 12 bytes generated by Cipher
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        // Prepend IV to ciphertext
        val combined = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, combined, 0, iv.size)
        System.arraycopy(ciphertext, 0, combined, iv.size, ciphertext.size)
        return Base64.encodeToString(combined, Base64.NO_WRAP)
    }

    /**
     * Decrypt a Base64-encoded string (IV + ciphertext) using AES-256-GCM.
     * Returns the original plaintext.
     */
    private fun decryptValue(encoded: String): String {
        val combined = Base64.decode(encoded, Base64.NO_WRAP)
        val iv = combined.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH, combined.size)
        val cipher = Cipher.getInstance(CIPHER_TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateSecretKey(), spec)
        val plainBytes = cipher.doFinal(ciphertext)
        return String(plainBytes, Charsets.UTF_8)
    }

    /**
     * Get the stored server URL (encrypted in DataStore, decrypted on read).
     */
    suspend fun getServerUrl(): String {
        return try {
            val encrypted = dataStore.data.first()[KEY_ENCRYPTED_SERVER_URL]
            if (encrypted.isNullOrBlank()) "" else decryptValue(encrypted)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to read/decrypt server URL", e)
            ""
        }
    }

    /**
     * Save the server URL (encrypted via Android Keystore, stored in DataStore).
     */
    suspend fun saveServerUrl(url: String) {
        try {
            val encrypted = if (url.isBlank()) "" else encryptValue(url)
            dataStore.edit { prefs ->
                prefs[KEY_ENCRYPTED_SERVER_URL] = encrypted
            }
            Log.d(TAG, "Server URL saved (encrypted via Keystore)")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to encrypt/save server URL", e)
        }
    }

    /**
     * Get the stored voice preference
     */
    val voiceFlow: Flow<String> = dataStore.data.map { prefs ->
        prefs[KEY_VOICE] ?: "bf_eleanor"
    }

    /**
     * Get the stored speed preference
     */
    val speedFlow: Flow<Float> = dataStore.data.map { prefs ->
        prefs[KEY_SPEED] ?: 1.0f
    }

    /**
     * Get the enabled state
     */
    val enabledFlow: Flow<Boolean> = dataStore.data.map { prefs ->
        prefs[KEY_ENABLED] ?: false
    }

    /**
     * Save voice preference
     */
    suspend fun saveVoice(voice: String) {
        dataStore.edit { prefs ->
            prefs[KEY_VOICE] = voice
        }
    }

    /**
     * Save speed preference
     */
    suspend fun saveSpeed(speed: Float) {
        dataStore.edit { prefs ->
            prefs[KEY_SPEED] = speed
        }
    }

    /**
     * Save enabled state
     */
    suspend fun saveEnabled(enabled: Boolean) {
        dataStore.edit { prefs ->
            prefs[KEY_ENABLED] = enabled
        }
    }

    /**
     * Save all TTS settings at once
     */
    suspend fun saveSettings(serverUrl: String, voice: String, speed: Float, enabled: Boolean) {
        // Save encrypted URL to DataStore
        saveServerUrl(serverUrl)

        // Save other settings to DataStore
        dataStore.edit { prefs ->
            prefs[KEY_VOICE] = voice
            prefs[KEY_SPEED] = speed
            prefs[KEY_ENABLED] = enabled
        }
        Log.d(TAG, "All TTS settings saved")
    }

    /**
     * Load all settings (for initialization)
     */
    suspend fun loadSettings(): TtsSettings {
        val serverUrl = getServerUrl()
        val prefs = dataStore.data.first()

        return TtsSettings(
            serverUrl = serverUrl,
            voice = prefs[KEY_VOICE] ?: "bf_eleanor",
            speed = prefs[KEY_SPEED] ?: 1.0f,
            enabled = prefs[KEY_ENABLED] ?: false
        )
    }

    /**
     * Clear all settings (for logout/reset)
     */
    suspend fun clearSettings() {
        dataStore.edit { it.clear() }
        Log.d(TAG, "All TTS settings cleared")
    }
}

/**
 * Data class for TTS settings
 */
data class TtsSettings(
    val serverUrl: String = "",
    val voice: String = "bf_eleanor",
    val speed: Float = 1.0f,
    val enabled: Boolean = false
) {
    val isConfigured: Boolean get() = serverUrl.isNotBlank()
}
